### ISSUE TITLE
ios safari 手机环境click未生效

### ISSUE THREAD

**Issue by NorviNS** [YunYouJun/cook#1]
https://github.com/YunYouJun/cook/blob/3fb58e6d460dd298f05dc0b5a8eb2ea85724edf4/src/components/ChooseFood.vue#L133

试着用手机打开了一下网页似乎点选之后并没有触发click

**Comment by YunYouJun** [comment]
emm，再试试？我没有 ios…… 不过电脑的 safari 正常，没有办法复现。

**Comment by YunYouJun** [comment]
因为无法复现，就先关闭了。

**Comment by NorviNS** [comment]
下午不行，可能是脚本问题，我刚去刷新重新进了一下又可以了……
