### ISSUE TITLE
建议添加一个「全部选择清空」按钮

### ISSUE THREAD

**Issue by EasonWong** [YunYouJun/cook#13]
RT并送上赞美&祝福

很好！牛逼！
很好！牛逼！
很好！牛逼！
很好！牛逼！
很好！牛逼！

**Comment by YunYouJun** [comment]
点击首页上方的大锅图标可以清空。

**Comment by YunYouJun** [comment]
emm，交互可能需要提醒地更明显一点。
有什么好的建议吗，但最好不用增加太多字。

**Comment by YunYouJun** [comment]
添加了一页专门的帮助页。https://github.com/YunYouJun/cook/commit/175346c43b9d7acf5864135f45cfc9d43912c9f3
