### ISSUE TITLE
建议添加视频作者名称

### ISSUE THREAD

**Issue by SevenOutman** [YunYouJun/cook#15]
有时候同一道菜会想看特定的作者的做法捏

**Comment by YunYouJun** [comment]
目前的数据并没有作者信息，进一步获取相对有些繁琐。
其次当目前的菜谱如果进一步添加显示作者信息，简化显得十分繁琐不美观，以及会导致诸多标签换行。
此外，我觉得抛弃预设的观念，尝试不同作者的视频也是容易发现惊喜的时候。
而如果是特定作者的粉丝，则通常可以直接关注 B 站账号观看，此需求的效果并不显著。

综上所述，目前并不考虑添加此功能。
如果您有其他的想法可以继续提出，若您可接受以上理由，可以关闭该 Issue。
