### ISSUE TITLE
好棒的工具

### ISSUE THREAD

**Issue by dfadsf32326** [YunYouJun/cook#2]
能否提一个意见，
就是可否增加 点击某个菜品或者厨具的时候  自动让没有相关菜谱的菜品 不能再点击了

**Comment by YunYouJun** [comment]
感谢你的建议，就是逻辑实现起来可能比较复杂，我试试效果。

**Comment by YunYouJun** [comment]
因为现在添加了精准匹配和模糊匹配，用户还是需要能够选中多个标签的，所以就不实现这个功能啦。

**Comment by dfadsf32326** [comment]
是选择多个标签呀 你可能没懂我的意思。 
就是。比如点击鸡肉。但是你这里的菜谱里没有同时使用鸡肉和牛肉的菜谱。那就使牛肉这个标签不能再选择。 
或者 选择午餐肉+猪肉的标签以后 点击 米饭 不会出现相应的菜谱 就让 米饭这个标签不能再被选择。
可以减少很多重复选择的次数 和 试错的次数
