### ISSUE TITLE
Maybe an unexpected behavior of docker build push action, the latest tag

### ISSUE THREAD

**Issue by henryclw** [YunYouJun/cook#26]
There should be a tag with latest.

In my fork, the default branch is main, then when the main branch is updated, there'll be a new image pushed to docker hub with the tag of latest

https://github.com/YunYouJun/cook/blob/50156534c23758043cfb3f4995488a69cf483a36/.github/workflows/docker-image.yml#L26

But now your default branch is dev, this mean the latest tag is always bounded with the branch dev, is this what you want?

**Comment by henryclw** [comment]
You may check your docker hub repo to see what tags there are

<https://hub.docker.com/r/yunyoujun/cook/tags>

**Comment by YunYouJun** [comment]
Yeah, i plan to remove `enable={{is_default_branch}} `.

Because ci will only be triggered by the main branch.

https://github.com/YunYouJun/cook/blob/50156534c23758043cfb3f4995488a69cf483a36/.github/workflows/docker-image.yml#L4-L7

Could there be other issues?

**Comment by henryclw** [comment]
> Yeah, i plan to remove `enable={{is_default_branch}} `.
> 
> Because ci will only be triggered by the main branch.
> 
> https://github.com/YunYouJun/cook/blob/50156534c23758043cfb3f4995488a69cf483a36/.github/workflows/docker-image.yml#L4-L7
> 
> Could there be other issues?

But the `latest` tag of docker is very important, because the default tag of docker image is `latest`

Say you run `docker pull nginx`, what actually it is doing is `docker pull nginx:latest`

So what do you want to do with the `latest` tag? Normally this is the latest release or the master/main branch.

**Comment by YunYouJun** [comment]
I don't think this contradicts what you said, I just want to remove `enable={{is_default_branch}}`, because the default `enable` is true, so it is still bound to the main branch, and main is also the representative of `latest`.

Was there any misunderstanding during this period?

**Comment by henryclw** [comment]
> I don't think this contradicts what you said, I just want to remove `enable={{is_default_branch}}`, because the default `enable` is true, so it is still bound to the main branch, and main is also the representative of `latest`.
> 
> Was there any misunderstanding during this period?

Oh, so what you want is only update docker image when the main branch is updated. And this means there's only one kind of docker image, the latest/main version, no nightly/dev version, right?

**Comment by YunYouJun** [comment]
Yeah, I created a new `dev` branch for development and merged into the `main` branch after stabilization, to avoid too many unnecessary docker builds.

**Comment by henryclw** [comment]
Okay, then this will be fine. Thank you for your kind reply, it's very nice of you.

**Comment by YunYouJun** [comment]
Thanks for your feedback. I set it in https://github.com/YunYouJun/cook/commit/d2534f748fa25ef0ce4838f956e55547d07db487.
