### ISSUE TITLE
有考虑增加随机推荐功能吗？另外我可否借鉴一下创意将其做成小程序

### ISSUE THREAD

**Issue by XR-stb** [YunYouJun/cook#33]

**Comment by YunYouJun** [comment]
随机推荐可以考虑。

制作小程序我不反对，但是值得提醒的是，之前有人做过一个小程序，但是被微信封了，具体原因我也不清楚。

**Comment by YunYouJun** [comment]
Feat added in https://github.com/YunYouJun/cook/commit/98a9a1f05e2461d40a922fd29d94751b7ccf7f5c.
