### ISSUE TITLE
请问可以增加搜索模式吗

### ISSUE THREAD

**Issue by virtual-puppy** [YunYouJun/cook#43]
想要输入【所有】已有的食材，然后挑选菜谱，不知道可以吗？
目前是只能一个一个试，感觉不是特别方便（；´д｀）而且有时候会蹦出来我没有的食材

**Comment by YunYouJun** [comment]
试试「生存模式」，可能就是你说的这种模式。

**Comment by virtual-puppy** [comment]
呜呜不好意思，没找到生存模式的切换在哪里……

**Comment by YunYouJun** [comment]
<img width="727" alt="image" src="https://user-images.githubusercontent.com/25154432/186463438-2baad5c5-469b-4673-bcc8-89d5fea50e15.png">

清一下网页缓存？可能更新没刷到。

**Comment by virtual-puppy** [comment]
手机能看到！但是不知为何电脑端看不到……呜呜谢谢

**Comment by YunYouJun** [comment]
@virtual-puppy 

![image](https://user-images.githubusercontent.com/25154432/186846274-52e88b16-46ec-4e92-a71c-712acfff012a.png)

![image](https://user-images.githubusercontent.com/25154432/186846310-f9b76d08-b1b1-4f37-a2d6-7d1332edc9b7.png)

试试清除数据再刷新。
