### ISSUE TITLE
是否可以在底部加入个人网站备案号

### ISSUE THREAD

**Issue by CatnlHelloWood** [YunYouJun/cook#49]
docker部署在国内的腾讯云，腾讯今天给我发邮件让我在网站底部添加备案号。个人域名已有备案号，请问有什么方法吗~

**Comment by CatnlHelloWood** [comment]
![67881d15aa9ba82803abf535995a02f](https://user-images.githubusercontent.com/88302654/232459563-b1ef953c-2e02-4442-a9a9-4bfc327dac35.png)

**Comment by YunYouJun** [comment]
有点疑惑，是你自建了一个吗，然后现在需要加上备案号？

如果是你自己部署的站点的话，自定义下就可以了。

**Comment by CatnlHelloWood** [comment]
直接用了你的docker搭建了，没有自定义。一直当一个前端展示的页面用~我大概看了下，就是我需要改下index，再生成一个docker镜像就行了对吧~

**Comment by YunYouJun** [comment]
是的，修改 html 很简单，你可以直接编辑一下。

https://github.com/YunYouJun/cook/blob/dev/src/components/BaseFooter.vue
