### ISSUE TITLE
居然没有麻婆豆腐！ 连麻婆豆腐包都有！怎么能没有麻婆豆腐！

### ISSUE THREAD

**Issue by cxFUxiao** [YunYouJun/cook#55]
### Clear and concise description of the problem

请添加麻婆豆腐

### Suggested solution

添加麻婆豆腐

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by YunYouJun** [comment]
有无视频链接推荐

**Comment by cxFUxiao** [comment]
【了不起的中国菜，大爷的麻婆豆腐，麻辣鲜香，配上米饭超好吃。-哔哩哔哩】 https://b23.tv/yZ3sCSR
