### ISSUE TITLE
https://cook.yunyoujun.cn挂了 我这是广东电信

### ISSUE THREAD

**Issue by Rimliya** [YunYouJun/cook#58]
### Describe the bug

![image](https://github.com/YunYouJun/cook/assets/48489813/e85f5796-84d5-4132-8775-4c60c66522c7)

### Reproduction

https://cook.yunyoujun.cn 499报错

### System Info

```Shell
win11 22635.2700，浏览器edge119.0.2151.44
```

### Used Package Manager

n/a

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YunYouJun** [comment]
https://stackoverflow.com/questions/12973304/possible-reason-for-nginx-499-error-codes

![image](https://github.com/YunYouJun/cook/assets/25154432/ee851137-b1eb-4135-b710-e5241cebd9c1)

相同网络下，移动端可以打开吗？

**Comment by Rimliya** [comment]
> https://stackoverflow.com/questions/12973304/possible-reason-for-nginx-499-error-codes
> 
> ![image](https://user-images.githubusercontent.com/25154432/281285188-ee851137-b1eb-4135-b710-e5241cebd9c1.png)
> 
> 相同网络下，移动端可以打开吗？

试了一下 我这里同wifi下移动端被拒绝链接，但是数据网络可以直接打开

**Comment by Rimliya** [comment]
> https://stackoverflow.com/questions/12973304/possible-reason-for-nginx-499-error-codes
> 
> ![image](https://user-images.githubusercontent.com/25154432/281285188-ee851137-b1eb-4135-b710-e5241cebd9c1.png)
> 
> 相同网络下，移动端可以打开吗？

排查结束了，是我这边本地卡巴斯基杀软的问题，不知道为甚么给拦截了

**Comment by YunYouJun** [comment]
> > [stackoverflow.com/questions/12973304/possible-reason-for-nginx-499-error-codes](https://stackoverflow.com/questions/12973304/possible-reason-for-nginx-499-error-codes)
> > ![image](https://user-images.githubusercontent.com/25154432/281285188-ee851137-b1eb-4135-b710-e5241cebd9c1.png)
> > 相同网络下，移动端可以打开吗？
> 
> 排查结束了，是我这边本地卡巴斯基杀软的问题，不知道为甚么给拦截了

2333，被反诈了（
